######################################################################
# Automatically generated by qmake (2.01a) Tue May 8 17:11:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qt
INCLUDEPATH += . qt

# Input
HEADERS += networking.hpp ui.hpp qt/chatwindow.h qt/ui_generic.hpp
FORMS += qt/chatwindow.ui
SOURCES += main.cpp networking.cpp qt/chatwindow.cpp
